permalink: /blog/:year/:month/:day/:title

baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Site specific context
title: Julia Solórzano
description: Julia Solórzano is a Security Experience Design Lead based in Durham, North Carolina.
